### PR TITLE
[CI/Build] Keep failed Clippy checks from reporting success

### PR DESCRIPTION
**Pull request by 1fanwang**
Related https://github.com/vllm-project/semantic-router/issues/3675

## Purpose

A failing Clippy run can be reported as successful when its diagnostics point outside the edited files. The Rust check now returns the failure status and shows the diagnostics.

This is the failed-command handling proposed in https://github.com/vllm-project/semantic-router/pull/3676, scoped to the accepted Developer Experience & Ecosystem issue above. The rest of that issue stays open.

## Test Plan

The regression invokes real Cargo offline against a dependency-free Rust crate. An unedited file produces ``error[E0425]: cannot find function `missing_symbol` in this scope``. It then repairs the fixture and checks the successful path. Only the separate failed-tool cases mock subprocess output.

From the PR checkout, with Python 3.12 and Rust/Clippy installed:

```bash
set -euo pipefail
support=tools/agent/scripts
regression="$support/tests/test_check_support.py"
testcase=RustClippyTests.test_compiler_failure_outside_changed_files_is_not_ignored
baseline=$(mktemp -d /tmp/router-clippy-before.XXXXXX)
git archive 58a62a0069c9c5c93d03a33b65b5991ee66c6d76 \
  "$support/check_support.py" "$support/go_lint_support.py" |
  tar -x -C "$baseline"
mkdir -p "$baseline/$support/tests"
cp "$regression" "$baseline/$regression"
before_exit=0
python3 "$baseline/$regression" "$testcase" -v || before_exit=$?
test "$before_exit" -eq 1
printf 'before_exit=%s\n' "$before_exit"
python3 "$regression" "$testcase" -v
printf 'after_exit=0\n'
```

## Test Result

| Scenario | Command | Result |
| --- | --- | --- |
| Baseline helper | `python3 "$baseline/$regression" "$testcase" -v` | Cargo fails with 101; the checker incorrectly returns 0. |
| Updated helper | `python3 "$regression" "$testcase" -v` | The checker returns 101 for the broken crate and 0 for the valid crate. |

<details><summary>Raw stdout</summary>

```text
invalid crate: cargo=101, check=0
before_exit=1
invalid crate: cargo=101, check=101
valid crate: check=0
after_exit=0
```

The unittest reports and expected baseline assertion failure are on stderr.

</details>

---
<details>
<summary>Semantic Router PR Checklist</summary>

- [x] PR title begins with exactly one bracketed category, such as `[Feature]`, `[Bug]`, `[Docs]`, `[Test]`, `[Research]`, `[Community]`, or `[CI/Build]`
- [x] The title does not stack prefixes such as `[Router][Docs]`; affected modules belong in labels and the PR body
- [x] The PR links an `accepted` issue with exactly one owner: one `wg/*` label for project work or `owner/maintainers` for repository governance
- [x] Commits in this PR are signed off with `git commit -s`
- [x] The Purpose, Test Plan, and Test Result sections reflect the actual scope, commands, and blockers for this change

</details>

See [CONTRIBUTING.md](../CONTRIBUTING.md) for the full contributor workflow and commit guidance.

### CODE REVIEW

**Review by Xunzhuo — APPROVED** [review]
The Clippy failure status is now preserved even when diagnostics are outside the edited files. The real Cargo regression and both failed-tool cases pass in the 397-case harness run, and the current-main integration is clean.

**Review by wilsonwu — APPROVED** [review]
LGTM
