### PR TITLE
[Bug] Restore ONNX RAG text windowing API

### LINKED ISSUE #3672: [Bug] ONNX router build fails after RAG windowing adds TextWindows
### Proposed Workgroup

Router Models & Inference Runtime

### Describe the bug

The ONNX router no longer compiles after #3650 added RAG query windowing. The shared router calls `candle_binding.TextWindows` and uses `candle_binding.TextWindow`, but these exports exist only in Candle. `src/semantic-router/go.onnx.mod` replaces the Candle module with `onnx-binding`, which does not implement them.

This is present on main at `e6184563b72514f9b9ed335d6a6405434d0688e2`. The affected binding, RAG source, module replacement, and Dockerfile are unchanged in #3483, whose CI exposes the failure.

### To Reproduce

On Linux amd64 with Docker, from that revision:

```bash
docker build -f tools/docker/Dockerfile.extproc --target go-builder .
```

The Candle binary builds, then the ONNX command fails:

```text
go build -modfile=go.onnx.mod -tags=onnx -ldflags="-w -s" -o ../../bin/router-onnx ./cmd

pkg/extproc/req_filter_rag_windowing.go:22:33: undefined: candle_binding.TextWindows
pkg/extproc/req_filter_rag_windowing.go:49:50: undefined: candle_binding.TextWindow
pkg/extproc/req_filter_rag_windowing.go:56:32: undefined: candle_binding.TextWindow
```

Observed in all three Kubernetes E2E profiles in [run 34348116029](https://github.com/vllm-project/semantic-router/actions/runs/34348116029): `external-gateway-responses`, `anthropic-shim`, and `response-api`.

### Expected behavior

The ONNX router builds against the shared binding API. RAG windowing uses the loaded ONNX embedding model's tokenizer and effective context limit, preserves valid byte ranges and overlapping coverage of long queries, and reports unavailable models as errors.

### Impact

The amd64 ExtProc image fails before deployment, so the affected E2E profiles cannot execute any test cases and PR Gate fails. Retrying the same revision does not resolve the missing symbols. The default Candle build still works.

### Additional context

- Introduced by #3650 (`1e0140c7d73837dcc2a63edec42b9f8d61dcc996`), which addressed #3385.
- Related prevention work: #2477 and #3320 cover ONNX build/test coverage. Their scope is broader than this production API regression.
- #3354, #2515, and #2888 do not currently add the missing windowing exports.
- A focused fix should restore the ONNX windowing contract and include regression coverage for the missing API and tokenizer window boundaries.

### PR DESCRIPTION
**Pull request by Kritoooo**
Closes #3672

## Purpose

Restore the ONNX `TextWindows` / `TextWindow` API required by RAG after #3650. With `go.onnx.mod` replacing the Candle binding, these missing exports prevent the ONNX router from compiling.

Use the loaded mmBERT tokenizer and context limit to produce overlapping UTF-8 byte ranges. Respect tokenizer truncation, a smaller caller limit, and the actual special-token budget; re-encode each substring to keep boundary changes within that budget. The Go wrapper validates inputs, and the Rust FFI owns and releases each returned offset array.

Add a dedicated ONNX CI workflow and Make targets for model-free tokenizer/FFI/Go regressions and an ONNX router build. The domain registry selects this workflow for ONNX source/tests, the shared Candle Go API, and ONNX module changes. Both PR and main validation gates include its result. Production Dockerfiles and Docker build-context rules are unchanged.

## Test Plan

```bash
make test-onnx-binding
make test-onnx-router-build
make harness-check
```

The binding target runs 10 Rust tokenizer/FFI regressions and the focused Go tests against the real native library. The router target builds the ONNX, ML, and NLP libraries and compiles the router with `go.onnx.mod` and the `onnx` tag. No model assets or external services are required. The focused Go command selects the new regression file; the broader legacy ONNX Go suite remains tracked by #2477.

## Test Result

- PASS locally: `make harness-check`, including 163 CI/harness tests, workflow contract validation, and actionlint.
- PASS locally: Make target dry-run, YAML lint, Black formatting, spelling, and `git diff --check`.
- PASS in GitHub CI on `306f785e`: [ONNX binding tests and router build](https://github.com/vllm-project/semantic-router/actions/runs/34364645592/job/102512963077) — 10 Rust regressions, both Go regressions against the native library, and the ONNX router build.
- PASS: the [final PR workflow](https://github.com/vllm-project/semantic-router/actions/runs/34364645592), including full pre-commit checks, both security scans, and PR Gate.
- Full native execution and router linking were run in GitHub CI. No full local suite was run.

---
<details>
<summary>Semantic Router PR Checklist</summary>

- [x] PR title begins with exactly one bracketed category.
- [x] The title does not stack prefixes; affected modules are described above.
- [ ] The PR links an `accepted` issue with exactly one owner. (#3672 has the proposed Workgroup and awaits acceptance.)
- [x] Commits in this PR are signed off with `git commit -s`.
- [x] Purpose, Test Plan, and Test Result reflect the actual scope and validation boundaries.

</details>

### CODE REVIEW

**Comment by Kritoooo** [comment]
Closing this PR because the original ONNX router build failure has already been fixed in #3634, merged into `main` as 2b7519a84aec96963b02a3534e82908beba33f76.

That change adds the ONNX `TextWindow` / `TextWindows` Go API and the corresponding Rust `get_text_windows` / `free_text_windows` implementation, resolving the missing-symbol build error tracked in #3672. The API restoration in this PR is therefore superseded.
