### ISSUE TITLE
[Bug] ONNX router build fails after RAG windowing adds TextWindows

### ISSUE THREAD

**Issue by Kritoooo** [vllm-project/semantic-router#3672]
### Proposed Workgroup

Router Models & Inference Runtime

### Describe the bug

The ONNX router no longer compiles after #3650 added RAG query windowing. The shared router calls `candle_binding.TextWindows` and uses `candle_binding.TextWindow`, but these exports exist only in Candle. `src/semantic-router/go.onnx.mod` replaces the Candle module with `onnx-binding`, which does not implement them.

This is present on main at `e6184563b72514f9b9ed335d6a6405434d0688e2`. The affected binding, RAG source, module replacement, and Dockerfile are unchanged in #3483, whose CI exposes the failure.

### To Reproduce

On Linux amd64 with Docker, from that revision:

```bash
docker build -f tools/docker/Dockerfile.extproc --target go-builder .
```

The Candle binary builds, then the ONNX command fails:

```text
go build -modfile=go.onnx.mod -tags=onnx -ldflags="-w -s" -o ../../bin/router-onnx ./cmd

pkg/extproc/req_filter_rag_windowing.go:22:33: undefined: candle_binding.TextWindows
pkg/extproc/req_filter_rag_windowing.go:49:50: undefined: candle_binding.TextWindow
pkg/extproc/req_filter_rag_windowing.go:56:32: undefined: candle_binding.TextWindow
```

Observed in all three Kubernetes E2E profiles in [run 34348116029](https://github.com/vllm-project/semantic-router/actions/runs/34348116029): `external-gateway-responses`, `anthropic-shim`, and `response-api`.

### Expected behavior

The ONNX router builds against the shared binding API. RAG windowing uses the loaded ONNX embedding model's tokenizer and effective context limit, preserves valid byte ranges and overlapping coverage of long queries, and reports unavailable models as errors.

### Impact

The amd64 ExtProc image fails before deployment, so the affected E2E profiles cannot execute any test cases and PR Gate fails. Retrying the same revision does not resolve the missing symbols. The default Candle build still works.

### Additional context

- Introduced by #3650 (`1e0140c7d73837dcc2a63edec42b9f8d61dcc996`), which addressed #3385.
- Related prevention work: #2477 and #3320 cover ONNX build/test coverage. Their scope is broader than this production API regression.
- #3354, #2515, and #2888 do not currently add the missing windowing exports.
- A focused fix should restore the ONNX windowing contract and include regression coverage for the missing API and tokenizer window boundaries.

**Comment by Xunzhuo** [comment]
Thanks — #3634 is now merged into `main` and restores the ONNX `TextWindow`/`TextWindows` Go API, the Rust windowing implementation, and focused coverage. The reported build contract is present again, so I’m closing this as completed.
