### ISSUE TITLE
[Feature] Confirm whether jailbreak detection is meant to be opt-in per routing recipe

### ISSUE THREAD

**Issue by theohsiung** [vllm-project/semantic-router#3127]
### Describe the feature

Confirm whether jailbreak detection is intended to be opt-in per routing recipe, and if not, make a recipe that omits it fail loudly rather than silently.

Tracing the request path on `main`, a guardrail only runs when the selected recipe's own decisions reference it:

```
extproc: evaluateSignalsForDecision
  → classifierForRequest(ctx)                    one classifier per recipe
  → EvaluateAllSignalsWithHeaders(...)           ForceEvaluateAll unset = false
  → getUsedSignals() → getUsedSignalsForDecisions(AllRoutingDecisions())
  → runSignalDispatchers:
        if isSignalTypeUsed(usedSignals, d.signalType) && ready[d.signalType]
```

Three consequences, each verified rather than inferred:

1. **Nothing classifier-related runs before a recipe is chosen.** `runRequestPreRoutingStages` calls `resolveEntrypointForRequest` first; everything before that is body parsing and model-name extraction. There is no stage that applies to all traffic regardless of recipe.
2. **`JailbreakRules` live in `Signals`, so they are per-recipe**, and `ConfigForRecipe` replaces the whole `Signals` block rather than merging it — a top-level rule is invisible once any recipe exists.
3. **`forceEvaluateAll` is only ever true from the classification API** (`pkg/services/classification.go`, `req.Options.EvaluateAllSignals`). The routing path never sets it.

So a recipe whose decisions do not reference `type: jailbreak` performs no jailbreak check, and nothing reports that. `prompt_guard` being under `global` does not change this: `ConfigForRecipe` copies the catalog, so the model is *available* to every recipe, but availability is not enforcement.

This may well be deliberate — recipes are independent routing strategies, and a strategy serving a trusted internal path may legitimately skip a guardrail. The gap is that there is no way to tell the two cases apart: "this recipe intentionally has no guardrail" and "someone added a recipe and forgot" look identical at config load, at startup, and at request time.

### Scope

First, a decision: is per-recipe opt-in the intended contract?

If yes, the ask is much smaller — document it explicitly (the safety-models tutorial currently does not say this), and consider a startup log line naming the recipes with no guardrail so it is at least visible.

If no, options worth weighing:

- a config-level warning or error when some recipes reference `type: jailbreak` and others do not, which is the shape most likely to indicate a mistake;
- an opt-in `required: true` on the module so an operator can declare that every recipe must carry it;
- a genuinely pre-recipe enforcement stage, which does not exist today and is the largest change.

Not in scope: changing which signals a recipe evaluates by default, or adding implicit inheritance from top-level signals into recipes — that inheritance is deliberately absent and should stay absent.

### Primary layer

signal

### Why this layer?

The behaviour is in signal dispatch (`runSignalDispatchers` gating on decision usage), even though the consequence is a safety one.

### Why do you need this feature?

A guardrail that silently does not run is indistinguishable from one that runs and finds nothing. Every other failure mode in this area has been closed recently — an unreachable backend fails loudly since #2930, and #2930 also added the `on_error: block` fail-closed path — but a recipe simply never invoking the guardrail is still silent. Worth an explicit answer either way, since the answer changes what the fail-closed work is actually guaranteeing.

### Additional context

Found while working through the interface discussion on #2760: https://github.com/vllm-project/semantic-router/issues/2760#issuecomment-5451364325

Independent of that discussion — it holds regardless of how backends end up being configured.

**Comment by Xunzhuo** [comment]
Closing with the architecture decision that prompt guard is an explicit, recipe-local opt-in, not an implicit global security layer. Backend migration remains in #3126, unknown-result policy in #3106, and explicit safe-route behavior in #3175.
