### PR TITLE
[Feature] Add Fusion analysis execution modes

### LINKED ISSUE #2865: [Feature] Make Fusion adaptive and support repeated self-sampling
## Goal

Coordinate evidence-backed Fusion cost reductions and bounded repeated self-sampling while preserving explicit analysis, synthesis, quorum, fallback, and accounting semantics.

## Proposed Workgroup

MoM & Routing

## Work item shape

This is a parent delivery issue under #2336. Repeated sampling, analysis-mode changes, execution gating, and protocol behavior are separate outcomes with different prerequisites; they must not be implemented as one unbounded pull request.

## Current-main baseline

Current Fusion always runs its structured analysis call and feeds that result into final synthesis. `include_analysis` controls whether analysis appears in the trace; it does not disable the call. Therefore there is no current bug in which a disabled analysis call runs unused. Skipping analysis requires a new, explicit execution contract.

## Ordered delivery map

1. Define and evaluate an explicit `analysis_mode` such as `separate`, `one_call`, or `none`, including how each mode changes the final prompt, usage, trace, and failure behavior.
2. Add repeated same-model sampling only after #2856 and #2861 provide shared panel and aggregate-budget contracts.
3. Compare direct, reduced-panel, and full Fusion execution against cached-panel and matched-budget baselines from #2858.
4. Add adaptive gating only after the evidence source and calibration contract are stable.
5. Add final protocol and streaming behavior after #3378 settles final-stage transport ownership.

## Configuration and API impact

Any analysis mode, sampling count, or adaptive gate is explicit, validated, bounded, and disabled or backward-compatible by default. `include_analysis` retains its current observability meaning.

## Non-goals

- Reclassify `include_analysis` as an execution toggle.
- Change grounding defaults; #2860 owns that evidence.
- Turn Fusion into Best-of-N selection.
- Add recursive Loopers, tree search, or arbitrary tool trajectories.
- Let request input weaken recipe-owned quorum, budget, or fallback policy.

## Completion signal

- [ ] Each child outcome names its prerequisite, budget, failure contract, and evaluation gate.
- [ ] Analysis-mode comparisons report quality, reliability, latency, token use, and failure behavior.
- [ ] Repeated samples have distinct provenance and aggregate accounting.
- [ ] Adaptive execution has deterministic evidence, calibration, and fallback.
- [ ] Protocol behavior remains explicit and covered after transport ownership is settled.

### PR DESCRIPTION
**Pull request by truddy0**
Related #2865

## Purpose

This PR delivers the first bounded outcome under #2865: explicit, recipe-owned Fusion analysis execution modes.

It adds:

- `separate`, preserving the existing panel + structured analysis + final synthesis behavior as the compatibility default;
- `one_call`, combining comparison and final synthesis in one judge call;
- `none`, synthesizing directly from panel responses without a distinct analysis artifact;
- validation and mirrored configuration across Go, DSL, Python, dashboard, canonical config, and documentation;
- deterministic accounting, prompt, failure, tool-boundary, and Looper E2E coverage.

`include_analysis` remains a trace-visibility setting and does not control model execution.

### Deferred parent outcomes

This PR intentionally does not close #2865:

- repeated same-model sampling waits for #2856 and #2861;
- matched-budget quality, reliability, latency, and cost evaluation belongs to #2858;
- adaptive mode selection waits for that evaluation and stable budget evidence;
- public mode-trace and final-stage streaming behavior remain owned by #3378.

The default remains `separate`; this PR makes reduced-call modes explicit opt-ins and does not claim a quality improvement from deterministic fixtures.

## Test Plan

- Targeted Go config, DSL, and Looper analysis-mode tests
- Python Fusion configuration tests
- Repository pre-commit and structure checks
- Recipe conformance and reference-config validation
- Looper Kubernetes E2E profile

## Test Result

- Go analysis-mode suites: passed
- Python configuration suite: 47 passed
- Recipe conformance: 50 passed
- Looper E2E: 3/3 passed
- Analysis-mode E2E verified:
  - aggregate tokens: `58 / 36 / 36`
  - iteration headers: `3 / 2 / 2`
  - expected mode-specific answers
  - no mode-only public `fusion` member
- Independent code review: no remaining findings

Known limitation: the pre-existing public Fusion trace envelope is not compatible with the strict response codec. This PR does not expand or claim to fix that transport contract; it is deferred to #3378.

### CODE REVIEW

File: src/semantic-router/pkg/looper/fusion.go [hunk 1]
```diff
@@ -70,6 +71,7 @@ type FusionFailedModel struct {
 }
 
 type FusionTrace struct {
+	AnalysisMode   string                `json:"analysis_mode,omitempty"`
```
Comment (Xunzhuo) [inline src/semantic-router/pkg/looper/fusion.go:74]: **Keep analysis mode out of the public trace**

Impact: `FusionTrace` is reused by the existing public fusion envelopes, and this JSON tag is always populated by `buildFusionTrace`. Ordinary JSON, tool, and streaming responses therefore gain `analysis_mode`, even though this PR explicitly defers public mode tracing to #3378; the new test currently codifies that leak.

Required change: Keep the mode field internal (or split the internal and public trace types), and add regressions across the public response paths proving it is not serialized until #3378 defines that contract.

File: website/docs/tutorials/algorithm/looper/fusion.md [hunk 2]
```diff
@@ -179,7 +196,14 @@ global:
...
 `global.integrations.looper.fusion` only registers direct request model names. It does not own route policy, a default route, judge selection, panel selection, concurrency, templates, or error handling.
 
-The judge model, analysis panel, concurrency, templates, and error policy belong under `routing.decisions[].algorithm.fusion`. Direct slug calls evaluate only Fusion-capable decisions, so `vllm-sr/fusion` cannot silently fall back to a normal single-model route. Request-level `plugins[].id = fusion` can still override the decision panel for one call; if no Fusion decision matched, a plugin override with `analysis_models` can provide a request-only panel.
+The judge model, analysis panel, analysis mode, concurrency, templates, and
+error policy belong under `routing.decisions[].algorithm.fusion`. Direct slug
+calls evaluate only Fusion-capable decisions, so `vllm-sr/fusion` cannot
+silently fall back to a normal single-model route. Request-level
+`plugins[].id = fusion` can still override the decision panel for one call; if
+no Fusion decision matched, a plugin override with `analysis_models` can
+provide a request-only panel. Requests cannot override `analysis_mode` or
```
Comment (Xunzhuo) [inline website/docs/tutorials/algorithm/looper/fusion.md]: **Enforce recipe-owned execution controls**

Impact: The runtime merges request config after the recipe and lets request values replace quorum, token/time limits, and `on_error`. A caller can therefore lower `min_successful_responses`, change budgets, or turn `fail` into `skip`, contradicting this documented guarantee that requests cannot weaken recipe-owned controls.

Required change: Reject or ignore request overrides for every recipe-owned control and test each protected field, so runtime behavior matches the published ownership contract.

**Review by Xunzhuo — COMMENTED** [review]
Thanks for the thorough mode coverage. I found two contract gaps that still need to be resolved.

File: website/docs/tutorials/algorithm/looper/fusion.md (hunk 2 above)
Comment (truddy0) [reply website/docs/tutorials/algorithm/looper/fusion.md]: Hi @Xunzhuo,

thank u for your comment. I have a question regarding the recipe configuration which I would like to learn more context. I think the default values of recipe are configured by yaml files, actually by this repo. If invokers would like a "low-quality" routing decision in some use cases, why do not accepting the override in the request to give the invokers freedom? Is there any deal breakers that such cases are not valid or do such cases could break something?  
Thanks.

File: src/semantic-router/pkg/looper/fusion.go (hunk 1 above)
Comment (truddy0) [reply src/semantic-router/pkg/looper/fusion.go:74]: fixed in commit 4d438d7 via adding a new struct `fusionPublicTrace` which does not contain `analysisMode`.

File: website/docs/tutorials/algorithm/looper/fusion.md (hunk 2 above)
Comment (truddy0) [reply website/docs/tutorials/algorithm/looper/fusion.md]: > **Enforce recipe-owned execution controls**
> 
> Impact: The runtime merges request config after the recipe and lets request values replace quorum, token/time limits, and `on_error`. A caller can therefore lower `min_successful_responses`, change budgets, or turn `fail` into `skip`, contradicting this documented guarantee that requests cannot weaken recipe-owned controls.
> 
> Required change: Reject or ignore request overrides for every recipe-owned control and test each protected field, so runtime behavior matches the published ownership contract.

regardless my question above, the fix of addressing this comment is pushed via commit b698b83

**Comment by truddy0** [comment]
FYI - after rebasing the PR with latest main, the builds fails because ONNX-build replaces the candle build with `onnx-binding`, but the lattter does not implement the `TextWindows`, which needs issue #3672

**Comment by truddy0** [comment]
> FYI - after rebasing the PR with latest main, the builds fails because ONNX-build replaces the candle build with `onnx-binding`, but the lattter does not implement the `TextWindows`, which needs issue #3672 

Already rebased with main again which carries #3672 fix.

**Review by Xunzhuo — APPROVED** [review]
Thanks!
